[build]
cmd = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/inquiries"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
